### ISSUE TITLE
Minor issue: Makefile for the Test run and output file names

### ISSUE THREAD

**Issue by abhimaniyar** [amoradinejad/limHaloPT#14]
1. After compiling the latest version of the code (with major improvements) successfully, I wanted to perform the test run suggested by the authors from the 'Test' folder. The 'Test' folder however, contains another 'makefile' and 'Output' folder which are already present in the main directory.

It seems like the authors expect the users to use this new 'makefile' to compile and test-run the code? If yes, then that requires modifying the 'makefile' again to include details of the CUBA and GSL libraries. This is probably unnecessary and can be avoided and the test run can probably be directly be run from the home directory with `./limHaloPT Test/test_LCDM.ini`. This, in turn, will produce output files in the 'Output' in the home directory. This makes the 'Output' folder in the 'Test' folder redundant. 

So based on the expectations of the authors, I suggest modifying the README file letting the user know 'how to run the test code' and 'where to look for the output produced'. If the intended test run is to be solely restricted to the 'Test' folder, README should be edited to let the user know to change the 'makefile' in the 'Test' folder.

2. After running the test code with `./limHaloPT Test/test_LCDM.ini`, I get the desired files in the 'Output' folder in the home directory. For example, following two files are produced: `pk_2h_comps_J0_z0.00..txt` and `pk_2h_comps_J0_z0.00.txt`. It seems that the first file contains names of the columns which are written in the second file. If this is expected, please ignore my comment. But if the authors intended to have the column names and values in the same folder, I would like to point out that this is not the case currently. As I said before though, this is a very minor issue.

**Comment by amoradinejad** [comment]
Thank you for the feedback. 

I address below the two points you mentioned in #14:
The “Test" folder intentionally has another makefile. The reason is that the tests can be extended without the need of compiling the main package. In other words, now limHaloPT is designed such that upon compilation, a static library, “liblimHaloPT.a” is created, which can be used an external library to other codes. Apart from being a test for the three main output functions of limHaloPT, the “Test.c” should also be considered as an example of  such  a code that uses this static library. The “Input” and "Output” subdirectories of “Test” directory are also designed to be local to this directory and independent of the main package. Indeed, this description was missing from the makefile. I have now modified the “Testing” section of makefile to reflect it. Moreover, I added comment about usage of limHaloPT as an external library in “Compilation” section of README.
The test code should not be run using ./limHaloPT.  Instead, it should be run using “./test  test_LCDM.ini”. The output files will be saved in “Output” sub-directory of “Test” directory. I have modified makefile to reflect this. As for the header of the output files, thanks for spotting an issue, which was the fact that when running the code with ./limHaloPT LCDM.ini , two files with the same name were generated, while only one should have been generated. This is now corrected. I just note that in the current version, when running the code for the file outputs that include the individual terms of the 1loop and the shot, if running the code at different redshifts and for different lines, the header is only saved for one of the files.


Best,
Azadeh

**Comment by abhimaniyar** [comment]
This is great, thanks for modifying this. It is very clear now. As long as the users make the necessary changes in the 'makefile' to link their libraries correctly, they can run the test codes separately much faster, and limHaloPT can be used as an external library which is nice! Closing this issue now.
